# Generated by Django 5.1 on 2024-12-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
