# Generated by Django 5.1 on 2024-12-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
