# Generated by Django 5.1 on 2024-12-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_user_email_alter_user_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desciption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
