# Generated by Django 5.1 on 2024-12-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_user_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='prject/1.jpg', upload_to='project/%Y/%m/%d/')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
