# Generated by Django 5.1 on 2024-12-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='project/%Y/%m/%d/'),
        ),
    ]
