# Generated by Django 5.1 on 2024-12-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='prject/1.jpg', upload_to='project/%Y/%m/%d/'),
        ),
    ]
