# Generated by Django 5.1 on 2024-12-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='autor',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Autor:'),
        ),
    ]
