# Generated by Django 5.1 on 2024-12-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='prject/1.jpg', upload_to='project/%Y/%m/%d/'),
        ),
    ]
