# Generated by Django 5.1 on 2024-12-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_category_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category_user',
        ),
    ]
