# Generated by Django 5.1 on 2024-12-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_delete_category_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
